### ISSUE TITLE
目標(~10/7) python環境構築

### ISSUE THREAD

**Issue by nonono22** [nonono22/yamisisi#2]
# python環境構築
## TODO
- [x] pythonを選ぶ理由リストを作る
- pythonの環境を作る
    - [x] python3のクリーンアップ
        - 余計なものが入ってるとたぶん途中で事故る
    - 必要module
        - [x] google tensor 
        - 多分これだけだと足りない気がする
            - 多分グラフとかもやるからmatplotとか
            - 増えたら増えた分だけログとる(このissueに書くでもなんでも)
    - [ ] @nonono22 も作れるようにどうやって入れたのかをログとる

---

10/7までにはいったん何かしら作れる環境にしてほしいかな

**Comment by nonono22** [comment]
# 余裕あればいいなタスクシリーズ
- [ ] どうやって目標の処理フローを作る?
    - deeplerningでもともとデータセットを学習させておく
    - 拾った画像を解析してdeeplerning結果と照らし合わせる   
        - deeplerningでできたモデルから近しい値をとる形になりそう?

**Comment by nonono22** [comment]
あ

**Comment by nonono22** [comment]
あ

**Comment by nonono22** [comment]
```
```で囲むとログ貼り付けっぽくなります

[コマンドプロンプト] $ python a
```

* クソ長いログはテキストファイルにはっつけてファイルをここに乗せてくれるのがいい


* 中途半端に長いログは以下の形式を使ってくれると楽

<details>
<summary>とじ込みのタイトル</summary>

```
```

</details>

**Comment by yamisisi** [comment]
Pythonを選ぶ理由
	インデントなどが厳密に決められてて可読性が高いので初学者でもとっつきやすい
	ディープラーニングに関するライブラリが充実している
	上記の理由からか、利用者がたくさんいて日本語での情報もたくさんある


過去に書いたコードを見た感じ必要そうなライブラリ
	Keras
	Matplotlib
	Numpy
	PIL
	Sklean(教師データをtrainとtestに分けたりするやつを使う)
	Glob(教師データファイルの読み込みとか)
	OpenCV(最終的にはカメラ入力から画像認識をさせたいので)

参考
https://www.aist-riss.jp/column/43394/

Visual Studio 2019
	Python 開発
		オプション
		Python miniconda
		Python Web サポート
		Python 3 64 ビット
		Live Share

Visual Studio 2017
	2019だと仕様が変わって参考にしたサイトと表記が色々違ったりAnacondaがなかったりしたので一応上記のサイトを参考に2017も入れた

CUDA Toolkit 11.1 Downloads

cuDNN v8.0.4 (September 28th, 2020), for CUDA 11.1
	ログインが必要なのでgoogleアカウントでログインした
	ダウンロードしたzipファイルを解凍して中身のフォルダ(3つ)をCUDA Toolkit(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1)にコピーした

Visual Studio 2019のPython 環境から環境を追加でConda環境を作成した。
インストールで選択したパッケージ
	Python(最新)
	keras

**Comment by nonono22** [comment]
# 残
- [ ] 参考サイトの手順を最後まで終わらせる
